---
title: "Day 1: Part-to-Whole"
author: "Keith Yoder"
date: '2022-04-01'
output:
  html_document:
    df_print: paged
---

```{r setup}
require(readr)
require(ggplot2)
require(magrittr)
require(forcats)
require(dplyr)
require(RColorBrewer)
require(ggfittext)
```

Data from [World Population Review](https://worldpopulationreview.com/us-cities/chicago-il-population) based on 2019 US Census data.


```{r import_data}
d <- read_csv('../data/CHIRaceEthnicity.csv')

# remove labels from small categories
d <- 
  d %>%
  mutate(label = case_when(
    Percent > 6 ~ Percent,
    TRUE ~ NA_real_
  ))
```

```{r plot}
png('Day1.png', width=800, height=600, units = 'px', res = 120)
p <- d %>%
  ggplot(aes(x=fct_reorder(RaceLabel, Percent), y=Percent, 
             fill=fct_reorder(RaceLabel, Percent),
             label = Percent)) +
  geom_bar(stat = 'identity', position='dodge') +
  #geom_text(size=4, position = position_stack(vjust = 0.5)) +
  theme_classic() +
  scale_fill_brewer(palette="Set3") +
  labs(title = "Chicago Racial Demographics",
       subtitle = "In 2019, Chicago was just under 50% White",
       caption = "Data: World Population Review | Graphic: @drkeithyoder | #30DayChartChallenge",
       fill = "Race", y = "%") +
  coord_flip() +
  theme(axis.title.y = element_blank(),
        legend.position = 'none',
        plot.caption = element_text(hjust = 0),
        plot.title =  element_text(hjust = -.8),
        plot.subtitle = element_text(hjust = -1.04))

p +
  geom_bar_text(position = 'dodge',
                outside = TRUE,
                min.size = 3,
                reflow = TRUE)

dev.off()
```

