---
title: "Day 4: Magical"
output: html_notebook
author: Keith Yoder
date: 2022-04-10
---

```{r setup, echo=FALSE, warning=FALSE}
require(tidyverse)
require(gtrendsR)
```

```{r import}
terms <- c('Vampire', 'Ghost', 'Witch')
d <- gtrends(terms, geo = rep('US', length(terms)))
d <- d$interest_over_time
d %>% write_csv('../data/magical_gtrends.csv')
d %>% glimpse()
```

```{r norm_counts}


d %>%
  ggplot(aes(date, hits, color=keyword)) +
  geom_line() +
  theme_classic() +
  theme(plot.background = element_rect(color = 'black', fill='black'),
        panel.background = element_rect(fill = 'grey10'),
        axis.ticks = element_line(color = 'grey80'),
        axis.title = element_text(color = 'grey80'),
        axis.text = element_text(color='grey80'),
        strip.text.x = element_text(color = 'grey80'),
        legend.background = element_rect(fill = 'black'),
        legend.text = element_text(color='grey80'),
        plot.title = element_text(color='grey80'),
        plot.subtitle = element_text(color='grey80'),
        plot.caption = element_text(color='grey80')) + 
  scale_color_manual(values = c('chocolate3', 'olivedrab4','goldenrod3')) +
  labs(y='Hits (relative to highest)', color=NULL, x='Date',
       title = 'Magical creatures at Halloween',
       subtitle = 'Google Trends shows increase hits in October',
       caption = 'Data: Google | Graphic: @drkeithyoder | #30DayChartChallenge',)


ggsave('Day4.png', width=6, height=4.5)
```

