---
title: 'Day 9: Statistics'
author: "Keith Yoder \n @drkeithyoder"
date: '2022-04-18'
output:
  html_document:
    df_print: paged
---

## Day 9 of \#30DayChartChallenge
Distributions: Statistics

```{r setup, message=FALSE, warning=FALSE}
require(tidyverse)
require(patchwork)
```

```{r sim}
# Beta
n <- 1e3
x <- seq(0, 1, length=n)

df = tibble(
  y = c(
    dbeta(x, 0.5, 0.5), dbeta(x, 0.5, 1), dbeta(x, 0.5, 2),
    dbeta(x, 1, 0.5), dbeta(x, 1, 1), dbeta(x, 1, 2),
    dbeta(x, 2, 0.5), dbeta(x, 2, 1), dbeta(x, 2, 2)
  ),
  x = rep(x, 9),
  alpha = rep(c(0.5, 1, 2), each=3*n),
  beta = rep(c(0.5, 1, 2), each=n, 3)
) %>%
  mutate(dist = str_c(alpha, '_', beta)) 

p_beta <- df %>%
  mutate(y = case_when(
    y > 12 ~ 12,
    TRUE ~ y
  )) %>%
  ggplot(aes(x=x, y, color=dist)) +
  geom_line(size=1) +
  theme_classic() +
  coord_cartesian(ylim=c(0, 5)) +
  scale_color_discrete(labels=c(
    'a=0.5 b=0.5', 'a=0.5 b=1', 'a=0.5 b=2',
    'a=1 b=0.5', 'a=1 b=1', 'a=1 b=2',
    'a=2 b=0.5', 'a=2 b=1', 'a=2 b=2')) +
  labs(title='Beta Distribution',
       color='Parameters', y='Probability')

# Gamma
x <- seq(0, 20, length=n)
df = tibble(
  y = c(
    dgamma(x, 1, 1), dgamma(x, 5, 1), dgamma(x, 10, 1),
    dgamma(x, 1, 2), dgamma(x, 5, 2), dgamma(x, 10, 2)
  ),
  x = rep(x, 6),
  alpha = rep(c(1, 5, 10), each=n, 2),
  beta = rep(c(1, 2), each=n*3)
) %>%
  mutate(dist = str_c(alpha, '_', beta)) 

p_gamma <- df %>%
  mutate(y = case_when(
    y > 12 ~ 12,
    TRUE ~ y
  )) %>%
  ggplot(aes(x=x, y, color=dist)) +
  geom_line(size=1) +
  theme_classic() +
  coord_cartesian(ylim=c(0, .5), xlim = c(0, 20)) +
  scale_color_discrete(labels=c(
    'a=1 b=1', 'a=5 b=1', 'a=10 b=1',
    'a=1 b=2', 'a=5 b=2', 'a=10 b=2')) +
  labs(title='Gamma Distribution',
       color='Parameters', y='Probability',
       caption='Graphic: @drkeithyoder | #30DayChartChallenge')

p_beta /
  p_gamma 
ggsave('Day9.png', width=6, height=6)
```

